version: '3.4'

services:
  api:
    build:
      context: .
      target: dev
    image: jaegeon/howlong:dev
    container_name: howlong-dev
    environment:
      APP_ENV: development
    volumes:
      - .:/app
    ports:
      - 8000:8000
